version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
- package-ecosystem: "docker"
  directories:
  - "/"
  - "/docker-transfer"
  schedule:
    interval: "monthly"
