{{- if .Values.tlsConfig }}
{{- if .Values.tlsConfig.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: tls-assets-nc-diag-agent
  labels:
    app.kubernetes.io/name: '{{ .Values.SERVICE_NAME }}'
    app.kubernetes.io/version: '{{ .Values.ARTIFACT_DESCRIPTOR_VERSION }}'
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: esc
type: Opaque
data:
  ca.crt : {{ .Values.tlsConfig.caCert | b64enc }}
  tls.crt : {{ .Values.tlsConfig.tlsCert | b64enc }}
  tls.key : {{ .Values.tlsConfig.tlsKey | b64enc }}
{{- end }}
{{- end }}
